In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
df1 = pd.read_excel('/content/FinalHinTrainTrac2_BackTran(clean).xlsx', index_col = 0) 

In [ ]:
df2 = pd.read_excel('/content/FinalHinDevTrac2_BackTran(clean).xlsx', index_col = 0)

In [ ]:
df1.head()

ID  ... Sub-task B
0     C4.131  ...       NGEN
1     C4.638  ...       NGEN
2    C38.598  ...       NGEN
3  C4.2101.1  ...       NGEN
4   C29.14.2  ...       NGEN

[5 rows x 4 columns]

In [ ]:
df2.head()

ID  ... Sub-task B
0    C38.9  ...       NGEN
1  C4.1510  ...       NGEN
2   C19.95  ...       NGEN
3   C4.281  ...       NGEN
4   C4.216  ...       NGEN

[5 rows x 4 columns]

In [ ]:
df1['Sub-task A'].value_counts()

CAG    2453
NAG    2245
OAG    1820
Name: Sub-task A, dtype: int64

In [ ]:
df2['Sub-task A'].value_counts()

CAG    602
OAG    582
NAG    578
Name: Sub-task A, dtype: int64

In [ ]:
df = pd.concat([df1, df2], ignore_index = True)

In [ ]:
df.head()

ID  ... Sub-task B
0     C4.131  ...       NGEN
1     C4.638  ...       NGEN
2    C38.598  ...       NGEN
3  C4.2101.1  ...       NGEN
4   C29.14.2  ...       NGEN

[5 rows x 4 columns]

In [ ]:
samples = df['data']

In [ ]:
samples[:5]

0    बॉलीवुड फिल्म देखने के समय तर्क घर में चोरके ए...
1                                        चुटिया फिल्म 
2    हमारे जाट बन्दे का खेने का अर्थ था मार्च डालुग...
3     फेमिनिस्म कैंसर की नारीवादी ये साही हैं संयुक...
4         अमृत आनंद अब तो जुड़े ही है उनको बोलो जुड़ने
Name: data, dtype: object

In [ ]:
labels = df['Sub-task A']

In [ ]:
labels[:5]

0    NAG
1    NAG
2    OAG
3    OAG
4    NAG
Name: Sub-task A, dtype: object

In [ ]:
print(len(samples))
print(len(labels))

8280
8280


In [ ]:
# Shuffle the data
seed = 1337
rng = np.random.RandomState(seed)
rng.shuffle(samples)
rng = np.random.RandomState(seed)
rng.shuffle(labels)

# Extract a training & validation split
validation_split = 0.2
num_validation_samples = int(validation_split * len(samples))
train_samples = samples[:-num_validation_samples]
val_samples = samples[-num_validation_samples:]
train_labels = labels[:-num_validation_samples]
val_labels = labels[-num_validation_samples:]

In [ ]:
train_labels = list(train_labels)
val_labels = list(val_labels)

In [ ]:
class_names = list(df['Sub-task A'].unique())
class_names

['OAG', 'CAG', 'NAG']

In [ ]:
class_index = [0, 1, 2] #NAG, CAG, OAG
i=0
for y in train_labels:
  if y=='NAG': train_labels[i] = 0
  elif y=='CAG': train_labels[i] = 1
  elif y == 'OAG': train_labels[i] = 2
  i=i+1

i=0
for y in val_labels:
  if y=='NAG': val_labels[i] = 0
  elif y=='CAG': val_labels[i] = 1
  elif y == 'OAG': val_labels[i] = 2
  i=i+1

In [ ]:
print(train_labels)
print(val_labels)

[2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 2, 1, 1, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 1, 2, 0, 2, 0, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 2, 1, 2, 1, 2, 1, 1, 2, 1, 0, 2, 2, 1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 0, 2, 2, 1, 0, 0, 1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 0, 0, 1, 2, 2, 2, 0, 2, 1, 0, 2, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 2, 1, 0, 1, 0, 0, 2, 2, 1, 1, 2, 0, 1, 2, 1, 0, 0, 2, 2, 0, 1, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 2, 0, 1, 2, 1, 0, 1, 1, 2, 2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 2, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 1, 2, 0, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 1, 2, 2, 

Creating a vocabulary index

In [ ]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

vectorizer = TextVectorization(max_tokens=20000, output_sequence_length=200)
text_ds = tf.data.Dataset.from_tensor_slices(train_samples).batch(128)
vectorizer.adapt(text_ds)

In [ ]:
vectorizer.get_vocabulary()[:5]

['', '[UNK]', 'हैं', 'के', 'है']

In [ ]:
output = vectorizer(["बिल्ली चटाई पर बैठ गयी"])
output.numpy()[0, :5]

array([1470,  186,   42, 2637,  852])

In [ ]:
voc = vectorizer.get_vocabulary()
word_index = dict(zip(voc, range(len(voc))))

In [ ]:
test = "बिल्ली चटाई पर बैठ गयी"
test = test.split()
print(test)
[word_index[w] for w in test]

['बिल्ली', 'चटाई', 'पर', 'बैठ', 'गयी']


[1470, 186, 42, 2637, 852]

Loading pre trained word embeddings

In [ ]:
from gensim.models import KeyedVectors

In [ ]:
word_vector = KeyedVectors.load_word2vec_format('/content/drive/MyDrive/indicnlp.v1.hi.vec')

In [ ]:
vocab = word_vector.vocab

In [ ]:
embeddings_index = {}
for k in vocab.keys():
  embeddings_index[k] = np.array([word_vector.word_vec(k)])

In [ ]:
embeddings_index['गाड़ी'].shape

(1, 300)

In [ ]:
print(embeddings_index['गाड़ी'])

[[-0.18459   -0.16825    0.22842    0.039162   0.35202    0.14852
  -0.1533     0.18437   -0.016483   0.13653    0.010091  -0.045647
   0.17754    0.50864   -0.15096    0.11702    0.11839   -0.041815
  -0.20078   -0.36772    0.070827  -0.45925   -0.3477     0.20979
   0.22356    0.14907   -0.19497    0.20422   -0.34571   -0.074452
  -0.33771   -0.067936  -0.1943    -0.14952   -0.1337    -0.090749
  -0.14532    0.064345  -0.44707    0.43862    0.04893    0.18071
   0.38901    0.11093   -0.20728   -0.048456   0.32397   -0.27911
   0.12347    0.062921   0.12542    0.15881   -0.046435   0.14135
   0.19208   -0.35628   -0.13255   -0.11908   -0.035328  -0.024825
   0.2242     0.42321   -0.061558   0.15229   -0.070308  -0.010775
  -0.065729   0.19989    0.016215   0.39801    0.0059314  0.3504
   0.17342    0.48351   -0.12432   -0.19586    0.22545   -0.15301
   0.24127   -0.012967  -0.098683   0.048035  -0.27929    0.43772
   0.090124  -0.21238    0.25137   -0.29371   -0.21291   -0.44505
  -0.

In [ ]:
num_tokens = len(voc) + 2
embedding_dim = 300
hits = 0
misses = 0
missed_word = []
# Prepare embedding matrix
embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
    else:
        misses += 1
        missed_word.append(word)
print("Converted %d words (%d misses)" % (hits, misses))

Converted 9625 words (2671 misses)


In [ ]:
(missed_word)

['',
 '[UNK]',
 'युतुबे',
 'हप्स',
 'चुटिये',
 'मुझ्े',
 'ज़्मक़मजोस',
 'चुटियापा',
 'रेसल्ट्स',
 'ब्क',
 'रनुं',
 'य्तु',
 'मदर्छोड़',
 'ज़्ज़्सऔदकीक',
 'लल्लांटॉप',
 'बोरादे',
 'एकडम',
 'म्तल्ब',
 'भ्ट',
 'भोस्डिके',
 'हहाहा',
 'य्क',
 'बेकचोड़ी',
 'ठप्पड',
 'छूट्या',
 'अछए',
 'वेदियो',
 'म्स्ट',
 'लॉन्दे',
 'लाइब्राल्स',
 'भोसई',
 'फामिनिस्ट',
 'ल्डकी',
 'लावड़े',
 'ब्सक',
 'स्वेताभ',
 'स्म्झ',
 'रामाधिर',
 'म्जा',
 'बख्वास',
 'ग्ल्ट',
 'क्रोगे',
 'क्रनी',
 'एस्ली',
 'एचएपीएस',
 'लाव्ड',
 'र्हेंगे',
 'भेंछोड',
 'बोहॉट',
 'तिक्टोक',
 'झंत',
 'जहील',
 'जरूर्ट',
 'ग्ल्टी',
 'एनीम',
 'व्ड़ो',
 'लोदु',
 'लाइब्रांडु',
 'म्क्ब',
 'मार्डो',
 'ब्फ',
 'ब्नटे',
 'बोल्के',
 'बेकचोड़',
 'बेंचोड',
 'बत्व',
 'फ्लीम',
 'फेमिनिस्तों',
 'पार्तिक',
 'ग्लोरिटी',
 'ग्फ',
 'गन्दुओ',
 'ख्रब',
 'कुम्फू',
 'स्म्झा',
 'व्हेत्सप्प',
 'विदियो',
 'ल्डकिया',
 'लेड्के',
 'लार्का',
 'लाउलिट',
 'रूगिस',
 'मारवाने',
 'मारवाओ',
 'भोसदिवालों',
 'भोसडाइक',
 'बरोथेर',
 'दारजे',
 'ठांकु',
 'ग्ण्डी',
 'क्रूँगा',
 'कुँकी',

In [ ]:
from tensorflow.keras.layers import Embedding

embedding_layer = Embedding(
    num_tokens,
    embedding_dim,
    embeddings_initializer=keras.initializers.Constant(embedding_matrix),
    trainable=False,
)

In [ ]:
from tensorflow.keras import layers

int_sequences_input = keras.Input(shape=(None,), dtype="int64")
embedded_sequences = embedding_layer(int_sequences_input)
x = layers.Conv1D(128, 5, activation="relu")(embedded_sequences)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(128, 5, activation="relu")(x)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(128, 5, activation="relu")(x)
x = layers.GlobalMaxPooling1D()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.5)(x)
preds = layers.Dense(len(class_names), activation="softmax")(x)
model = keras.Model(int_sequences_input, preds)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, None)]            0         
_________________________________________________________________
embedding (Embedding)        (None, None, 300)         3689400   
_________________________________________________________________
conv1d (Conv1D)              (None, None, 128)         192128    
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, None, 128)         0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, None, 128)         82048     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, None, 128)         0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, None, 128)         82048 

In [ ]:
x_train = vectorizer(np.array([[s] for s in train_samples])).numpy()
x_val = vectorizer(np.array([[s] for s in val_samples])).numpy()

y_train = np.array(train_labels)
y_val = np.array(val_labels)

In [ ]:
print(y_train)
print(y_val)

[2 1 1 ... 2 1 2]
[2 1 1 ... 2 2 0]


In [ ]:
model.compile(
    loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"]
)
model.fit(x_train, y_train, batch_size=128, epochs=20, validation_data=(x_val, y_val))

Epoch 1/20
52/52 [==============================] - 26s 478ms/step - loss: 1.0359 - acc: 0.4784 - val_loss: 0.9440 - val_acc: 0.5857
Epoch 2/20
52/52 [==============================] - 25s 474ms/step - loss: 0.8942 - acc: 0.6055 - val_loss: 0.8821 - val_acc: 0.5954
Epoch 3/20
52/52 [==============================] - 25s 475ms/step - loss: 0.7625 - acc: 0.6756 - val_loss: 0.9361 - val_acc: 0.5882
Epoch 4/20
52/52 [==============================] - 25s 474ms/step - loss: 0.6640 - acc: 0.7385 - val_loss: 0.9891 - val_acc: 0.5598
Epoch 5/20
52/52 [==============================] - 25s 473ms/step - loss: 0.5326 - acc: 0.7936 - val_loss: 0.9665 - val_acc: 0.5906
Epoch 6/20
52/52 [==============================] - 25s 472ms/step - loss: 0.4442 - acc: 0.8370 - val_loss: 1.0182 - val_acc: 0.6099
Epoch 7/20
52/52 [==============================] - 24s 472ms/step - loss: 0.3547 - acc: 0.8838 - val_loss: 0.8755 - val_acc: 0.6612
Epoch 8/20
52/52 [==============================] - 24s 472ms/step - 

In [ ]:
string_input = keras.Input(shape=(1,), dtype="string")
x = vectorizer(string_input)
preds = model(x)
end_to_end_model = keras.Model(string_input, preds)

probabilities = end_to_end_model.predict(
    [["मादरचोद चुटिया संघी, यही देश डुबाएंगे"]]
)

class_names[np.argmax(probabilities[0])]

'OAG'